//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjct_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyReg
    {
        public int c_id { get; set; }
        public string c_name { get; set; }
        public string c_address { get; set; }
        public string c_phone { get; set; }
        public string c_email { get; set; }
        public string c_location { get; set; }
    }
}
