//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjct_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_tab
    {
        public int Jb_id { get; set; }
        public int Cmp_id { get; set; }
        public string Title { get; set; }
        public string Experience { get; set; }
        public string Skill { get; set; }
        public int No_vaccancy { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
    }
}
