//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjct_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReg
    {
        public int u_id { get; set; }
        public string u_name { get; set; }
        public int u_age { get; set; }
        public string u_address { get; set; }
        public string u_phone { get; set; }
        public string u_email { get; set; }
        public string qualification { get; set; }
        public string experience { get; set; }
        public string skills { get; set; }
        public string photo { get; set; }
        public string resume { get; set; }
    }
}
